"""Curate a small set of SigmaHQ rules into ``data/examples/``.

Run once after ``scripts/fetch_sigmahq.py``. The selected rules are
manually picked for instructional value: each demonstrates a different
observation type and detection shape (mapping form, list-of-mappings,
filter blocks, glob conditions). Each output file gets an attribution
header noting the upstream source + the SigmaHQ commit it came from.

Re-running overwrites previously-curated files. Bumping the SigmaHQ
commit pin in ``scripts/fetch_sigmahq.py`` and re-running this is the
quarterly recalibration loop.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS = REPO_ROOT / "sigmahq-rules"
OUT_DIR = REPO_ROOT / "data" / "examples"

# Each tuple: (source path under sigmahq-rules/, output filename in data/examples/,
# why-this-is-instructive blurb that goes in the example's index entry).
SELECTIONS: list[tuple[str, str, str]] = [
    (
        "rules/windows/process_creation/proc_creation_win_conhost_headless_powershell.yml",
        "process_creation_headless_powershell.yml",
        "process_creation with selection + filter blocks; condition uses 'and not'.",
    ),
    (
        "rules/windows/file/file_event/file_event_win_anydesk_artefact.yml",
        "file_event_anydesk_artefact.yml",
        "file_event match on TargetFilename suffix — the 'malware drops a file at path X' shape.",
    ),
    (
        "rules/windows/registry/registry_set/registry_set_aedebug_persistence.yml",
        "registry_set_aedebug_persistence.yml",
        "registry_set persistence detection — TargetObject + Details fields.",
    ),
    (
        "rules/windows/network_connection/net_connection_win_certutil_initiated_connection.yml",
        "network_connection_certutil_outbound.yml",
        "network_connection initiated by certutil; Image + Initiated + Destination.",
    ),
    (
        "rules/windows/dns_query/dns_query_win_anonymfiles_com.yml",
        "dns_query_anonymfiles.yml",
        "dns_query for a malware-hosting service domain.",
    ),
    (
        "rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_obfuscated_iex.yml",
        "ps_script_obfuscated_iex.yml",
        "ps_script (EventID 4104) detecting an obfuscated Invoke-Expression pattern.",
    ),
]


def main() -> int:
    if not CORPUS.is_dir():
        print(f"SigmaHQ corpus not found at {CORPUS}")
        print("Run `uv run python scripts/fetch_sigmahq.py` first.")
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Capture the corpus commit hash so attribution is precise.
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=CORPUS, text=True
        ).strip()
    except subprocess.SubprocessError:
        commit = "unknown"

    for src_rel, dest_name, _why in SELECTIONS:
        src = CORPUS / src_rel
        if not src.is_file():
            print(f"  SKIP missing: {src_rel}")
            continue
        dest = OUT_DIR / dest_name
        attribution = (
            f"# Curated from SigmaHQ at commit {commit[:12]}\n"
            f"# Source: https://github.com/SigmaHQ/sigma/blob/{commit}/{src_rel}\n"
            f"# License: MIT (per SigmaHQ root LICENSE).\n"
            f"# Original Sigma authorship preserved below; intel2sigma uses this as an example.\n"
            f"#\n"
        )
        dest.write_text(attribution + src.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"  copied {src_rel} -> {dest.relative_to(REPO_ROOT)}")

    # Manifest mapping file: id -> path + description, consumed by
    # web/load.py's example listing.
    manifest = OUT_DIR / "_index.yml"
    lines = ["# Curated example index. Generated by scripts/curate_examples.py.\n"]
    lines.append(f"corpus_commit: {commit}\n")
    lines.append("examples:\n")
    for _src_rel, dest_name, why in SELECTIONS:
        ex_id = dest_name.removesuffix(".yml")
        lines.append(f"  - id: {ex_id}\n")
        lines.append(f"    file: {dest_name}\n")
        lines.append(f"    description: {why!r}\n")
    manifest.write_text("".join(lines), encoding="utf-8")
    print(f"  manifest -> {manifest.relative_to(REPO_ROOT)}")

    # Trigger ruamel auto-format pass so the example files are tidy.
    print("\nDone. Examples shipped under data/examples/.")
    print("Re-run after bumping the SigmaHQ commit pin in scripts/fetch_sigmahq.py.")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
