"""Curate a small set of SigmaHQ rules into ``data/examples/``.

Run once after ``scripts/fetch_sigmahq.py``. The selected rules are
manually picked for instructional value: each demonstrates a different
observation type and detection shape (mapping form, list-of-mappings,
filter blocks, glob conditions). Each output file gets an attribution
header noting the upstream source + the SigmaHQ commit it came from.

Re-running overwrites previously-curated files. Bumping the SigmaHQ
commit pin in ``scripts/fetch_sigmahq.py`` and re-running this is the
quarterly recalibration loop.
"""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORPUS = REPO_ROOT / "sigmahq-rules"
OUT_DIR = REPO_ROOT / "intel2sigma" / "data" / "examples"

# Each tuple: (source path under sigmahq-rules/, output filename in data/examples/,
# why-this-is-instructive blurb that goes in the example's index entry).
SELECTIONS: list[tuple[str, str, str]] = [
    (
        "rules/windows/process_creation/proc_creation_win_conhost_headless_powershell.yml",
        "process_creation_headless_powershell.yml",
        "process_creation with selection + filter blocks; condition uses 'and not'.",
    ),
    (
        "rules/windows/file/file_event/file_event_win_anydesk_artefact.yml",
        "file_event_anydesk_artefact.yml",
        "file_event match on TargetFilename suffix — the 'malware drops a file at path X' shape.",
    ),
    (
        "rules/windows/registry/registry_set/registry_set_aedebug_persistence.yml",
        "registry_set_aedebug_persistence.yml",
        "registry_set persistence detection — TargetObject + Details fields.",
    ),
    (
        "rules/windows/network_connection/net_connection_win_certutil_initiated_connection.yml",
        "network_connection_certutil_outbound.yml",
        "network_connection initiated by certutil; Image + Initiated + Destination.",
    ),
    (
        "rules/windows/dns_query/dns_query_win_anonymfiles_com.yml",
        "dns_query_anonymfiles.yml",
        "dns_query for a malware-hosting service domain.",
    ),
    (
        "rules/windows/powershell/powershell_script/posh_ps_invoke_obfuscation_obfuscated_iex.yml",
        "ps_script_obfuscated_iex.yml",
        "ps_script (EventID 4104) detecting an obfuscated Invoke-Expression pattern.",
    ),
]


def _manifest_content(commit: str) -> str:
    """Render ``_index.yml`` — id → path + description.

    Consumed by ``web/load.py``'s example listing. Built as a string so
    ``--check-only`` can compare it against what is on disk without
    writing anything.
    """
    lines = ["# Curated example index. Generated by scripts/curate_examples.py.\n"]
    lines.append(f"corpus_commit: {commit}\n")
    lines.append("examples:\n")
    for _src_rel, dest_name, why in SELECTIONS:
        ex_id = dest_name.removesuffix(".yml")
        lines.append(f"  - id: {ex_id}\n")
        lines.append(f"    file: {dest_name}\n")
        lines.append(f"    description: {why!r}\n")
    return "".join(lines)


def main() -> int:
    # --check-only is documented in docs/recalibration.md step 5 as a
    # re-validation that touches nothing. It was never implemented: the
    # flag parsed as an unrecognised argument, was ignored, and the
    # script rewrote every example anyway. During the 2026-Q3 cycle that
    # silently produced seven modified files from what the runbook
    # presents as a read-only check.
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Report what would change without writing anything.",
    )
    args = parser.parse_args()
    check_only = bool(args.check_only)

    if not CORPUS.is_dir():
        print(f"SigmaHQ corpus not found at {CORPUS}")
        print("Run `uv run python scripts/fetch_sigmahq.py` first.")
        return 1

    if not check_only:
        OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Capture the corpus commit hash so attribution is precise.
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=CORPUS, text=True
        ).strip()
    except subprocess.SubprocessError:
        commit = "unknown"

    drifted: list[str] = []
    for src_rel, dest_name, _why in SELECTIONS:
        src = CORPUS / src_rel
        if not src.is_file():
            print(f"  SKIP missing: {src_rel}")
            continue
        dest = OUT_DIR / dest_name
        attribution = (
            f"# Curated from SigmaHQ at commit {commit[:12]}\n"
            f"# Source: https://github.com/SigmaHQ/sigma/blob/{commit}/{src_rel}\n"
            f"# License: MIT (per SigmaHQ root LICENSE).\n"
            f"# Original Sigma authorship preserved below; intel2sigma uses this as an example.\n"
            f"#\n"
        )
        content = attribution + src.read_text(encoding="utf-8")
        if check_only:
            current = dest.read_text(encoding="utf-8") if dest.is_file() else None
            state = "MISSING" if current is None else ("drift" if current != content else "ok")
            if state != "ok":
                drifted.append(dest_name)
            print(f"  {state:>7}  {dest.relative_to(REPO_ROOT)}")
            continue
        dest.write_text(content, encoding="utf-8")
        print(f"  copied {src_rel} -> {dest.relative_to(REPO_ROOT)}")

    manifest = OUT_DIR / "_index.yml"
    manifest_content = _manifest_content(commit)
    if check_only:
        current = manifest.read_text(encoding="utf-8") if manifest.is_file() else None
        if current != manifest_content:
            drifted.append(manifest.name)
            print(f"    drift  {manifest.relative_to(REPO_ROOT)}")
        if drifted:
            names = ", ".join(drifted)
            print(f"\n{len(drifted)} file(s) differ from the pinned corpus: {names}")
            print("Re-run without --check-only to refresh them.")
            return 1
        print("\nAll curated examples match the pinned corpus.")
        return 0
    manifest.write_text(manifest_content, encoding="utf-8")
    print(f"  manifest -> {manifest.relative_to(REPO_ROOT)}")

    # Trigger ruamel auto-format pass so the example files are tidy.
    print("\nDone. Examples shipped under data/examples/.")
    print("Re-run after bumping the SigmaHQ commit pin in scripts/fetch_sigmahq.py.")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
